apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Golang template
  description: Just a golang template
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Repository name
          ui:autofocus: true

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template-v2
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is a test
        repoUrl: github.com?repo=${{ parameters.name }}&owner=backstage-ct
        defaultBranch: main
        repoVisibility: public

