# escaping-syntax for backstage template: https://roadie.io/docs/scaffolder/writing-templates/#escaping-syntax

name: release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ '${{ github.actor }}' }}
          password: ${{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ '${{ github.repository }}' }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ '${{ github.repository }}' }}:${{ '${{ github.sha }}' }},ghcr.io/${{ '${{ github.repository }}' }}:latest
          labels: ${{ '${{ steps.meta.outputs.labels }}' }}
