apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ${{ values.name }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/backstage-ct/${{ value.name }}.git
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated: {}
