apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    backstage.io/kubernetes-id: argocd
spec:
  destination:
    namespace: ${{ values.name }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/backstage-ct/${{ values.name }}.git
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: {}
