apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name | dump }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ${{ values.name | dump }}
  template:
    metadata:
      labels:
        app: ${{ values.name | dump }}
    spec:
      containers:
      - image: ghcr.io/backstage-ct/${{ values.name | dump }}:latest
        name: ${{ values.name | dump }}
        ports:
        - containerPort: 80
